update

diff --git a/.github/workflows/restassured.yml b/.github/workflows/restassured.yml
--- a/.github/workflows/restassured.yml
+++ b/.github/workflows/restassured.yml
@@ -28,6 +28,8 @@ jobs:
     - name: Execute regression test suite
       run: mvn clean test
 
-    - name: test
-      run: |
-        ls
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: './Testing/Backend/API/RestAssured/target/surefire-reports/*.xml'
